#!/bin/sh

LOG_DIR=/var/log/datadog
INSTALL_DIR=/opt/datadog-agent
OPT_APP_DIR="$INSTALL_DIR/Datadog Agent.app"
APP_CONF_DIR="/Applications/Datadog Agent.app/Contents/Resources"

# We log stdout & stderr of this script
LOG_FILE=$LOG_DIR/postinstall.log
mkdir -p $LOG_DIR
exec > $LOG_FILE 2>&1

# Determine current user
CURRENT_USER=$(ps aux | grep "CoreServices/Installer" | grep -v grep | awk '{print $1;}')

# OS/Distro Detection
DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue 2>/dev/null || uname -s)

if [ $DISTRIBUTION = "Darwin" ]; then
  # Reinstall is really different: 
  # the app is extracted directly where the old version is
  if [ -e "$OPT_APP_DIR" ]; then
    # Prepare log dir
    chown -R $CURRENT_USER:admin $LOG_DIR
    chmod 755 $LOG_DIR

    # Installing the app
    rm -rf /Applications/Datadog\ Agent.app
    mv $INSTALL_DIR/Datadog\ Agent.app /Applications
  fi

  sed "s|AGENT_BASE|$APP_CONF_DIR|; s|USER_NAME|$CURRENT_USER|" $INSTALL_DIR/Datadog\ Agent.app/Contents/Resources/com.datadoghq.Agent.plist.example > $INSTALL_DIR/Datadog\ Agent.app/Contents/Resources/com.datadoghq.Agent.plist
  
  # Copying existing conf is one exists
  if [ -e "/tmp/datadog.conf" ]; then
    mv -f "/tmp/datadog.conf" "$APP_CONF_DIR/"
    mv -f "/tmp/conf.d/*" "$APP_CONF_DIR/conf.d"
    cp -n "/tmp/checks.d/*" "$APP_CONF_DIR/checks.d"
    rm -rf /tmp/datadog.conf /tmp/conf.d /tmp/checks.d
  # Or copying default
  else
    cp "$APP_CONF_DIR/datadog.conf.example" "$APP_CONF_DIR/datadog.conf"
  fi

  # Correct rights
  chown $CURRENT_USER:admin "$APP_CONF_DIR/datadog.conf"
  chown -R $CURRENT_USER:admin "$APP_CONF_DIR/conf.d" "$APP_CONF_DIR/checks.d"

  # Error if app not properly installed
  if [ ! -e "$APP_CONF_DIR/datadog.conf" ]; then
    exit 1
  fi

  # Launch the app
  sudo -u $CURRENT_USER "$APP_CONF_DIR/../MacOS/datadog-agent" start || true
  sudo -u $CURRENT_USER open -a 'Datadog Agent.app'
fi
exit 0
