#!/bin/sh

LOG_DIR=/var/log/datadog
INSTALL_DIR=/opt/datadog-agent
TEMP_DIR=/opt/datadog-agent/tmp
CONFIG_DIR=/opt/datadog-agent/etc

# OS/Distro Detection
DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue 2>/dev/null || uname -s)

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}


if [ $DISTRIBUTION = "Darwin" ]; then
  # Prepare log dir
  mkdir -p ${LOG_DIR} || error_exit "Cannot create ${LOG_DIR}!"
  chown -R root:admin $LOG_DIR
  chmod 775 $LOG_DIR

  # Install executable in PATH
  # ln -sf $INSTALL_DIR/bin/datadog-agent /usr/bin/datadog-agent
  # chmod 755 /usr/bin/datadog-agent
  sed "s|AGENT_BASE|$INSTALL_DIR|; s|USER_NAME|$(whoami)|" $INSTALL_DIR/launchd/com.datadoghq.Agent.plist.example > $INSTALL_DIR/launchd/com.datadoghq.Agent.plist


  # Set proper rights to the admin group
  mkdir -p $TEMP_DIR
  chown -R root:admin /opt/datadog-agent $TEMP_DIR
  touch $TEMP_DIR/collector.log $TEMP_DIR/forwarder.log $TEMP_DIR/dogstatsd.log $TEMP_DIR/supervisord.log
  chown root:admin $TEMP_DIR/collector.log $TEMP_DIR/forwarder.log $TEMP_DIR/dogstatsd.log $TEMP_DIR/supervisord.log
  chmod 775 $TEMP_DIR
  chmod 664 $TEMP_DIR/collector.log $TEMP_DIR/forwarder.log $TEMP_DIR/dogstatsd.log $TEMP_DIR/supervisord.log
  chmod 775 $CONFIG_DIR $CONFIG_DIR/conf.d $CONFIG_DIR/checks.d
  chmod 664 $CONFIG_DIR/datadog.conf.example $CONFIG_DIR/supervisor.conf $CONFIG_DIR/conf.d/*

  # Copying default conf file is none exist
  if ! [ -e $CONFIG_DIR/datadog.conf ]; then
    cp $CONFIG_DIR/datadog.conf.example $CONFIG_DIR/datadog.conf
    chmod 664 $CONFIG_DIR/datadog.conf
  fi

  # Installing the app if it exists
  if [ -d $INSTALL_DIR/Datadog\ Agent.app ]; then
    chmod a+x $INSTALL_DIR/Datadog\ Agent.app/Contents/MacOS/run.sh
    mv $INSTALL_DIR/Datadog\ Agent.app /Applications
  fi
fi
exit 0
