#!/bin/sh

CONFIG_DIR=/etc/dd-agent
LOG_DIR=/var/log/datadog
INSTALL_DIR=/opt/datadog-agent

# OS/Distro Detection
DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue 2>/dev/null || uname -s)

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p ${LOG_DIR} || error_exit "Cannot create ${LOG_DIR}!"

if [ $DISTRIBUTION = "Darwin" ]; then
  # Copy conf
  mkdir -p /etc/dd-agent
  cp -R $INSTALL_DIR/conf/* /etc/dd-agent
  ln -sf $INSTALL_DIR/bin/datadog-agent /usr/bin/datadog-agent
  sed "s|AGENT_BASE|$INSTALL_DIR|; s|USER_NAME|$(whoami)|" $INSTALL_DIR/launchd/com.datadoghq.Agent.plist.example > $INSTALL_DIR/launchd/com.datadoghq.Agent.plist

  chmod 755 /usr/bin/datadog-agent

  # Set proper rights to the current user
  chown -R $(whoami):nogroup ${CONFIG_DIR}
  chown -R $(whoami):nogroup ${LOG_DIR}
  chown -R root:nogroup /opt/datadog-agent
fi
exit 0
